### PR TITLE
Remove "aasIdentifier" from POST /submodels

### LINKED ISSUE #369: [Bug]: Wrong endpoint to POST Submodel
### Contact Details

_No response_

### Describe the bug

The REST endpoint to POST a new Submodel requires an AAS-ID which is not according to the specification. Although the aasIdentifier parameter is marked as optional, the server fails when omitting it.

### To reproduce

POST /shells
POST /submodels

### Screenshots

```bash

```

### Expected Behaviour

It should be possible to have SMs that are not linked to an AAS.

### Version

_No response_

### Operating System

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by juileetikekar**
# Description

This PR removes the query parameter "aasIdentifier" from POST /submodels endpoint, so as to make it conformant with the specifications and make it interoperable with other solutions.

Fixes # (issue)
Fixes #369 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested manually with Swagger UI.

## Screenshots (if appropriate):

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/AasxServerStandardBib/Services/AdminShellPackageEnvironmentService.cs [hunk 1]
```diff
@@ -599,49 +600,97 @@ public List<ISubmodel> GetAllSubmodels()
...
-                if (aasFound)
+                foreach (var package in foundPackages)
                 {
-                    newSubmodel.SetAllParents(DateTime.UtcNow);
-                    aas.Submodels ??= new List<IReference>();
-                    aas.Submodels.Add(newSubmodel.GetReference());
-                    _packages[packageIndex].AasEnv.Submodels.Add(newSubmodel);
+                    var packageIndex = package.Key;
+                    _packages[packageIndex].AasEnv!.Submodels ??= new List<ISubmodel>();
+                    _packages[packageIndex].AasEnv!.Submodels!.Add(newSubmodel);
```
Comment (MSchmoecker) [inline src/AasxServerStandardBib/Services/AdminShellPackageEnvironmentService.cs:653]: Unless I'm missing something obvious, this code path doesn't make a lot sense.

The old behavior was to add the submodel directly to the aasIdentifier, without needing to append the submodel to the AAS submodel list. Of course this isn't possible without an aasIdentifier anymore.

However, now `foundPackages` is the list of AASs that already include the new submodel identifier and yet we add the submodel to the AAS submodel list. This results in the submodel entry being duplicated. Usually this doesn't happen because the submodel is new and not found in any AAS anyway.

**Comment by juileetikekar** [comment]
Thank you for reporting the issue. I will try to reproduce it , and get back to you.
